# Generated by perplexity via o1
#!/usr/bin/env python2
import os
import glob
import sys
import time

def measure_listdir(directory, repeats):
    start = time.time()
    for _ in range(repeats):
        _ = os.listdir(directory)
    return (time.time() - start) / repeats

def measure_glob(directory, repeats):
    start = time.time()
    pattern = os.path.join(directory, '*')
    for _ in range(repeats):
        _ = glob.glob(pattern)
    return (time.time() - start) / repeats

def main():
    if len(sys.argv) != 3:
        print("Usage: python2 test_performance.py <directory> <repeats>")
        sys.exit(1)
    directory = sys.argv[1]
    repeats = int(sys.argv[2])

    listdir_time = measure_listdir(directory, repeats)
    glob_time = measure_glob(directory, repeats)

    print("os.listdir:       {:.6f} seconds per run".format(listdir_time))
    print("glob.glob('*'):   {:.6f} seconds per run".format(glob_time))

if __name__ == '__main__':
    main()
